// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeZlTcDM7FVszPzRsFxJbeDAP5cNP9y6s',
    appId: '1:324960274839:android:3b2c0a2190391409bc9cd2',
    messagingSenderId: '324960274839',
    projectId: 'shikshasutram',
    storageBucket: 'shikshasutram.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh4W5Q6VHmp-8uhCBi7wyCevYCa9Uth5A',
    appId: '1:324960274839:ios:241cb5e12c53ce9abc9cd2',
    messagingSenderId: '324960274839',
    projectId: 'shikshasutram',
    storageBucket: 'shikshasutram.firebasestorage.app',
    iosBundleId: 'com.dbvertex.pearllinedentocare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBywU9EABLZdwV5uvZEKedV1oaN_TiOdQQ',
    appId: '1:324960274839:web:0f638f9062595db9bc9cd2',
    messagingSenderId: '324960274839',
    projectId: 'shikshasutram',
    authDomain: 'shikshasutram.firebaseapp.com',
    storageBucket: 'shikshasutram.firebasestorage.app',
    measurementId: 'G-EFXLR6158H',
  );
}
